import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.db.base_class import Base

class Battle(Base):
    __tablename__ = "battles"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    creator_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)
    battle_type = Column(String, default="1v1") # 1v1, group, team
    status = Column(String, default="pending") # pending, active, completed, cancelled
    
    start_date = Column(DateTime(timezone=True), nullable=False)
    end_date = Column(DateTime(timezone=True), nullable=False)
    
    stake_amount = Column(Integer, default=0, nullable=False) # Amount required per participant
    pot_size = Column(Integer, default=0, nullable=False) # Total coins in escrow
    
    winner_id = Column(UUID(as_uuid=True), nullable=True) # User ID of the winner, or team ID
    ai_report = Column(String, nullable=True) # Generated by AI Referee post-battle
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    participants = relationship("BattleParticipant", back_populates="battle", cascade="all, delete-orphan")


class BattleParticipant(Base):
    __tablename__ = "battle_participants"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    battle_id = Column(UUID(as_uuid=True), ForeignKey("battles.id"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    
    team_name = Column(String, nullable=True)
    status = Column(String, default="invited") # invited, accepted, rejected
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    battle = relationship("Battle", back_populates="participants")
