"""Add streak tracking and battle checkins

Revision ID: 4d2c2c24beac
Revises: 2abd3c1cb07b
Create Date: 2026-07-10 00:09:14.242475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2c2c24beac'
down_revision: Union[str, Sequence[str], None] = '2abd3c1cb07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('battle_id', sa.UUID(), nullable=True))
    op.alter_column('check_ins', 'goal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_check_ins_battle_id'), 'check_ins', ['battle_id'], unique=False)
    op.create_foreign_key(None, 'check_ins', 'battles', ['battle_id'], ['id'])
    op.add_column('users', sa.Column('highest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_checkin_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_checkin_date')
    op.drop_column('users', 'highest_streak')
    op.drop_constraint(None, 'check_ins', type_='foreignkey')
    op.drop_index(op.f('ix_check_ins_battle_id'), table_name='check_ins')
    op.alter_column('check_ins', 'goal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('check_ins', 'battle_id')
    # ### end Alembic commands ###
