"""Add mock_stake to goals

Revision ID: e29cbbcb6324
Revises: ebc5510bffc4
Create Date: 2026-07-09 20:21:27.424929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29cbbcb6324'
down_revision: Union[str, Sequence[str], None] = 'ebc5510bffc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('mock_stake', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'mock_stake')
    # ### end Alembic commands ###
