"""add index to commitment_score

Revision ID: e637ef667b45
Revises: e29cbbcb6324
Create Date: 2026-07-09 20:34:08.377947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e637ef667b45'
down_revision: Union[str, Sequence[str], None] = 'e29cbbcb6324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_commitment_score'), 'users', ['commitment_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_commitment_score'), table_name='users')
    # ### end Alembic commands ###
