"""Add image_url to check_ins

Revision ID: ec9144bef7e3
Revises: 453dd968ab90
Create Date: 2026-07-09 23:18:45.584193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9144bef7e3'
down_revision: Union[str, Sequence[str], None] = '453dd968ab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_ins', 'image_url')
    # ### end Alembic commands ###
